version: '2.3'

services:

  jupyterlab-torch:
    image: yhavinga/nvidia-pytorch-tensorflow-scipy-jupyter-addons:pytorch1.0.1-tensorflow2.0.0-cuda10.0-py3.7-ubuntu18.04
    build:
      context: .
    runtime: nvidia
    restart: always
    environment:
      - NV_GPU=0
#      - JUPYTER_ENABLE_LAB=1
    volumes:
      - ./workspace:/home/jovyan/work
      - ./dotjupyter:/home/jovyan/.jupyter
    ports:
      - 8888:8888
